---
- name: restart httpd when file update
  hosts: all
  tasks:
          - name: copy content
            copy:
                content: "Ansible Ex447 practice"
                dest: /root/ansible447
            notify: restart_httpd

  handlers:
          - name: restart_httpd
            service:
                name: httpd
                state: restarted
...                
